name: Build Minecraft Plugin
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: |
        # Create Maven structure
        mkdir -p src/main/java/com/spvico/coolplugin
        mkdir -p src/main/resources
        # Move files to correct locations
        [ -f Main.java ] && mv Main.java src/main/java/com/spvico/coolplugin/
        [ -f plugin.yml ] && mv plugin.yml src/main/resources/
        [ -f config.yml ] && mv config.yml src/main/resources/
        # Create simple Maven build
        cat > pom.xml << 'EOF'
        <project>
          <modelVersion>4.0.0</modelVersion>
          <groupId>com.spvico</groupId>
          <artifactId>CoolPlugin</artifactId>
          <version>1.0</version>
          <build>
            <plugins>
              <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                  <source>17</source>
                  <target>17</target>
                </configuration>
              </plugin>
              <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                  <execution>
                    <phase>package</phase>
                    <goals>
                      <goal>single</goal>
                    </goals>
                    <configuration>
                      <archive>
                        <manifest>
                          <mainClass>com.spvico.coolplugin.Main</mainClass>
                        </manifest>
                      </archive>
                      <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                      </descriptorRefs>
                    </configuration>
                  </execution>
                </executions>
              </plugin>
            </plugins>
          </build>
          <dependencies>
            <dependency>
              <groupId>org.spigotmc</groupId>
              <artifactId>spigot-api</artifactId>
              <version>1.20.1-R0.1-SNAPSHOT</version>
              <scope>provided</scope>
            </dependency>
          </dependencies>
          <repositories>
            <repository>
              <id>spigotmc-repo</id>
              <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
            </repository>
          </repositories>
        </project>
        EOF
        mvn clean compile assembly:single
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: CoolPlugin
        path: target/*.jar
