name: Build Cool Plugin
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Create JAR manually
      run: |
        # Create a simple JAR without Maven
        mkdir -p build/classes
        mkdir -p build/resources
        
        # Compile Java files
        javac -d build/classes src/main/java/com/spvico/coolplugin/Main.java
        
        # Copy resources
        cp src/main/resources/* build/resources/ 2>/dev/null || true
        
        # Create JAR
        jar cf CoolPlugin.jar -C build/classes . -C build/resources .
        
        # Create proper structure for plugin.yml
        mkdir -p META-INF
        echo "Manifest-Version: 1.0" > META-INF/MANIFEST.MF
        echo "Main-Class: com.spvico.coolplugin.Main" >> META-INF/MANIFEST.MF
        
        jar ufm CoolPlugin.jar META-INF/MANIFEST.MF
        
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: CoolPlugin
        path: CoolPlugin.jar
