name: Build Cool Plugin
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build with Maven
      run: |
        # Create proper Maven directory structure
        mkdir -p src/main/java/com/spvico/coolplugin
        mkdir -p src/main/resources
        
        # Move Java files to correct package location
        find . -name "*.java" -exec mv {} src/main/java/com/spvico/coolplugin/ \; 2>/dev/null || true
        
        # Move YAML files to resources
        find . -name "*.yml" -exec mv {} src/main/resources/ \; 2>/dev/null || true
        
        # Download Spigot API
        wget -O lib/spigot-api.jar https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot-api/1.20.1-R0.1-SNAPSHOT/spigot-api-1.20.1-R0.1-SNAPSHOT.jar
        
        # Compile and package
        mvn clean compile
        mvn package
        
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: CoolPlugin
        path: target/*.jar
